version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    ignore: 
      update-types: [ "version-update:semver-patch" ]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore: 
      update-types: [ "version-update:semver-patch" ]
